### PR TITLE
Feature/72 upscale only resizing

### PR DESCRIPTION
**Pull request by dcharbonnier**

### CODE REVIEW

**Comment by dcharbonnier** [comment]
documentation is missing for now but if you can give a first feeback

**Comment by dcharbonnier** [comment]
any news on this ? maintaining a fork is anoying

**Comment by elad** [comment]
@dcharbonnier sync the code so there are no conflicts, update the README, and I'll merge it.

**Comment by dcharbonnier** [comment]
replaced by #148

**Pull request closed without merging**
