### PR TITLE
Support Node.js 14

### PR DESCRIPTION
**Pull request by abetomo**
An additional fix to #195 allows it to compile in Node.js14.
Better than #195 because I'm using 'Nan::To'.

### CODE REVIEW

**Comment by terion-name** [comment]
Why this not still merged? It works and is needed

**Comment by TimWolla** [comment]
I remember having received push privileges back when the Open Open Source concept was introduced for this repository. I am no longer using this. The software I used this in was replaced by a reimplementation in Rust. Thus I don't have a need for this and I am unable to actually test this. For some reason I am still watching this repository, though. As this got my attention I will try to help out anyway.

I am seeing that Travis is green and I eyeballed the diff. It's not looking *incorrect* to me. So I'll just go ahead and merge this. I am unable to publish to npm, though. But my understanding is that the version there is completely out of date anyway.

Thanks.

**Comment by TimWolla** [comment]
> I remember having received push privileges back when the Open Open Source concept was introduced for this repository.

Found the old discussion about this: https://github.com/elad/node-imagemagick-native/pull/102#issuecomment-140145154

**Comment by TimWolla** [comment]
It appears that Travis is dog slow lately. The builds for master are still queued. I'm happy to merge GitHub Actions based CI if you ping me.

**Pull request merged**
